// <auto-generated />
using CE.ArchiveWebSites.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CE.ArchiveWebSites.Core.Migrations
{
    [DbContext(typeof(ArchivesDbContext))]
    [Migration("20191016114424_AddShoppingCart")]
    partial class AddShoppingCart
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CE.ArchiveWebSites.Core.Models.MediaRecordComment", b =>
                {
                    b.Property<int>("MediaRecordCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MediaRecordId")
                        .HasColumnType("int");

                    b.HasKey("MediaRecordCommentId");

                    b.ToTable("MediaRecordComments");

                    b.HasData(
                        new
                        {
                            MediaRecordCommentId = 1,
                            Comment = "That's lovely",
                            CreatedBy = "Catherine",
                            MediaRecordId = 1
                        },
                        new
                        {
                            MediaRecordCommentId = 2,
                            Comment = "Not great",
                            CreatedBy = "Catherine",
                            MediaRecordId = 2
                        },
                        new
                        {
                            MediaRecordCommentId = 3,
                            Comment = "That's a lovely Playbill",
                            CreatedBy = "Catherine",
                            MediaRecordId = 3
                        },
                        new
                        {
                            MediaRecordCommentId = 4,
                            Comment = "Not a great Playbill",
                            CreatedBy = "Catherine",
                            MediaRecordId = 4
                        });
                });

            modelBuilder.Entity("CE.ArchiveWebSites.Core.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Finish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MediaRecordId")
                        .HasColumnType("int");

                    b.Property<bool>("Sepia")
                        .HasColumnType("bit");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("CE.ArchiveWebSites.Core.Models.WebCard", b =>
                {
                    b.Property<int>("WebCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contents")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WebCardId");

                    b.ToTable("WebCards");
                });
#pragma warning restore 612, 618
        }
    }
}
